apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels: {{- include "open5gs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: gtpc
    port: {{ .Values.gtpc }}
    targetPort: gtpc
    protocol: UDP
  publishNotReadyAddresses: true
  selector: {{- include "open5gs.labels" . | nindent 4 }}
