apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-smf-Gx
  labels: {{- include "open5gs.labels" . | nindent 4 }}
spec:
  ports:
  - name: diameter
    port: {{ .Values.Gx }}
    targetPort: diameter
    protocol: SCTP
  publishNotReadyAddresses: true
  selector: {{- include "open5gs.labels" . | nindent 4 }}
