apiVersion: v2
name: core
description: Open5GS Core Network
type: application
version: 0.1.0
icon: https://open5gs.org/assets/img/open5gs-logo.png
dependencies:
- name: hss
  version: "*"
  repository: file://../hss
- name: smf
  version: "*"
  repository: file://../smf
- name: upf
  version: "*"
  repository: file://../upf
- name: pcrf
  version: "*"
  repository: file://../pcrf
