apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-upf-gtpu
  labels: {{- include "open5gs.labels" . | nindent 4 }}
spec:
  ports:
  - name: gtpu
    port: {{ .Values.gtpu }}
    targetPort: gtpu
    protocol: UDP
  publishNotReadyAddresses: true
  selector: {{- include "open5gs.labels" . | nindent 4 }}
