{{- if .Values.metrics }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-upf-metrics
  labels: {{- include "open5gs.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.metrics }}
    targetPort: metrics
    protocol: TCP
  publishNotReadyAddresses: true
  selector: {{- include "open5gs.labels" . | nindent 4 }}
{{- end }}
