apiVersion: v2
name: ims
description: IP Multimedia Subsystem
type: application
version: 0.1.0
appVersion: 6.0.4
dependencies:
- name: coredns
  version: "*"
  repository: file://../coredns
- name: rtpengine
  version: "*"
  repository: file://../rtpengine
- name: dra
  version: "*"
  repository: file://../dra
