apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "valkey.name" . }}
  labels: {{- include "valkey.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "valkey.name" . }}
  replicas: {{ add 1 .Values.cluster.replicas | mul .Values.cluster.primaries }}
  podManagementPolicy: Parallel
  selector:
    matchLabels: {{- include "valkey.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "valkey.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: db
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        command:
        - valkey-server
        - /etc/valkey/valkey.conf
        ports:
        - name: client
          containerPort: {{ .Values.ports.valkey }}
          protocol: TCP
        - name: cluster
          containerPort: {{ .Values.ports.bus }}
          protocol: TCP
        startupProbe:
          exec:
            command:
            - valkey-cli
            - ping
        livenessProbe:
          exec:
            command:
            - valkey-cli
            - ping
        readinessProbe:
          exec:
            command:
            - valkey-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 6
          failureThreshold: 10
          successThreshold: 1
        resources: {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: conf
          mountPath: /etc/valkey
      volumes:
      - name: conf
        configMap:
          name: {{ include "valkey.name" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
