apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtpengine.name" . }}
  labels:
    {{- include "rtpengine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: control
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: UDP
  selector:
    {{- include "rtpengine.selectorLabels" . | nindent 4 }}
