apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rtpengine.name" . }}
spec:
  selector:
    matchLabels: {{- include "rtpengine.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "rtpengine.name" . }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{- include "rtpengine.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        args:
        - --config-section=$(HOSTNAME)
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: control
          containerPort: {{ .Values.service.port }}
          protocol: UDP
        - name: monitor
          containerPort: {{ .Values.monitor.port }}
          protocol: TCP
        startupProbe:
          httpGet:
            path: /ping
            port: monitor
        livenessProbe:
          httpGet:
            path: /ping
            port: monitor
        readinessProbe:
          httpGet:
            path: /ping
            port: monitor
        {{- with .Values.resources }}
        resources: {{- toYaml . | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: conf
          mountPath: /etc/rtpengine
      volumes:
      - name: conf
        configMap:
          name: {{ include "rtpengine.name" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
