apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "coredns.fullname" .) .Values.service.name }}
  labels: {{- include "coredns.labels" . | nindent 4 }}
spec:
  selector:
    {{- if .Values.service.selector }}
    {{- toYaml .Values.service.selector | nindent 4 }}
    {{- else }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    {{- if .Values.isClusterService }}
    k8s-app: {{ template "coredns.k8sapplabel" . }}
    {{- end }}
    app.kubernetes.io/name: {{ template "coredns.name" . }}
    {{- end }}
  {{- with .Values.service.spec.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .Values.service.clusterIPs }}
  clusterIPs: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.externalIPs }}
  externalIPs: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  ports:
  {{- include "coredns.servicePorts" . | nindent 2 -}}
  type: {{ default "ClusterIP" .Values.serviceType }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.trafficDistribution }}
  trafficDistribution: {{ . }}
  {{- end }}
